# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest -v
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -vv
  sonarqube:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
#     - name: SonarQube Scan
#       uses: sonarsource/sonarqube-scan-action@master
#       with:
#         args: >
#           -Dsonar.projectKey=GAparsimony 
#           -Dsonar.sources=.
#           -Dsonar.login=${{ secrets.SONAR_LOGIN }}
#           -Dsonar.password=${{ secrets.SONAR_PASSWORD }}
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=GAparsimony 
          -Dsonar.sources=.
          -Dsonar.organization=misantam
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  readthedocs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/main' }}
    steps:
    - name: webook readthedocs.io
      run: |
            curl -X POST -d "branches=main" -d "token=${{ secrets.READTHEDOC_TOKEN }}" ${{ secrets.READTHEDOC_URL }}

  # with: 

  # docker-example:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: run_sonarqube  
  #     uses: docker://sonarqube:latest
  #     with:
  #       # entrypoint: /opt/box/box
  #       args: version
